import { profile, stats, projects, skills, experience, certifications } from './data.js';

const tagList = (items) => `<div class="tags">${items.map((item) => `<span>${item}</span>`).join('')}</div>`;
const heading = (title, subtitle) => `<div class="heading"><h2>${title}<i>.</i></h2><p>${subtitle}</p></div>`;
const iconMap = { 'Golang':['go','original'], 'Python':['python','original'], 'Java':['java','original'], 'Microservices':['docker','original'], 'REST APIs':['fastapi','original'], 'Kafka':['apachekafka','original'], 'Distributed Systems':['graphql','plain'], 'Django':['django','plain'], 'Concurrency':['go','original'], 'Docker':['docker','original'], 'Kubernetes':['kubernetes','plain'], 'Terraform':['terraform','original'], 'AWS':['amazonwebservices','original-wordmark'], 'GCP':['googlecloud','original'], 'OCI':['oracle','original'], 'GitHub Actions':['githubactions','original'], 'Grafana':['grafana','original'], 'LLM Applications':['python','original'], 'Prompt Engineering':['python','original'], 'RAG':['python','original'], 'Agentic Workflows':['python','original'], 'LangChain':['python','original'], 'LangGraph':['python','original'], 'PostgreSQL':['postgresql','original'], 'MySQL':['mysql','original'], 'Redis':['redis','original'], 'NoSQL':['mongodb','original'], 'React':['react','original'], 'Next.js':['nextjs','original'], 'Elasticsearch':['elasticsearch','original'], 'Object Oriented Programming':['java','original'] };
const skillIcon = (name) => { const [icon, variant] = iconMap[name] || ['devicon','plain']; return `https://cdn.jsdelivr.net/gh/devicons/devicon/icons/${icon}/${icon}-${variant}.svg`; };

document.querySelector('#app').innerHTML = `
  <div class="stars"></div>
  <header class="nav-wrap"><nav class="nav"><a class="brand" href="#hero">Dipesh<span>.</span></a><button class="menu" aria-label="Toggle navigation">☰</button><div class="nav-links"><a href="#hero" class="active">Home</a><a href="#about">About</a><a href="#projects">Projects</a><a href="#skills">Skills</a><a href="#experience">Experience</a><a href="#highlights">Highlights</a><a href="#certifications">Certificates</a><a href="#contact">Contact</a></div></nav></header>
  <main>
    <section id="hero" class="hero"><div class="hero-glow"></div><div class="hero-content"><p>Hey, I'm</p><h1>DIPESH KUMAR SINGH</h1><div class="role-pill"><span></span>${profile.role}</div><p class="hero-statement">Backend Engineer building scalable<br/>distributed systems and AI-powered platforms.</p><div class="hero-actions"><a href="https://drive.google.com/file/d/1DQbl-xcsN0sLR4o444PUXAvQabla6A5B/view?usp=drive_link" target="_blank" rel="noreferrer" class="button primary download-button">Resume <b>⇩</b></a><a href="#contact" class="button secondary">Let's Connect <b>↗</b></a></div></div><div class="scroll-note">SCROLL TO EXPLORE <span>↓</span></div></section>
    <section id="about" class="section narrow">${heading('About Me', 'Get to know me better')}<div class="about-layout"><div class="portrait"><img src="assets/dipesh-kumar-singh.png" alt="Dipesh Kumar Singh"/><div class="portrait-shine"></div><div class="portrait-caption">Backend · Cloud · AI</div><div class="dots"><i></i><i></i><i></i><i></i></div></div><div class="about-copy"><p>${profile.summary}</p><div class="stat-grid">${stats.map(([num,label]) => `<div><strong>${num}</strong><span>${label}</span></div>`).join('')}</div></div></div></section>
    <section id="projects" class="section wide">${heading('Projects', 'A selection of my recent work')}<div class="project-grid">${projects.map((project) => `<article class="project-card">${project.image ? `<a class="project-visual screenshot" href="${project.link}" target="_blank" rel="noreferrer"><img src="${project.image}" alt="${project.title} preview"/><small>${project.eyebrow}</small></a>` : `<div class="project-visual"><span>${project.icon}</span><small>${project.eyebrow}</small></div>`}<div class="project-body"><h3>${project.title}</h3><p>${project.description}</p><ul>${project.features.map((feature) => `<li>${feature}</li>`).join('')}</ul>${tagList(project.stack)}${project.link ? `<a class="card-link" href="${project.link}" target="_blank" rel="noreferrer">Visit project <b>↗</b></a>` : ''}</div></article>`).join('')}</div></section>
    <section id="skills" class="section narrow">${heading('Skills & Expertise', 'A collection of technologies I’m proficient with, from languages to cloud platforms and AI tooling')}<div class="skills-stack">${skills.map((group) => `<div class="skill-row"><h3>${group.name}</h3><div class="skill-tiles">${group.items.map((item) => `<div class="skill-tile"><img src="${skillIcon(item)}" alt="${item} logo" onerror="this.style.display='none';this.nextElementSibling.style.display='grid'"/><b class="skill-fallback">${item.slice(0,2)}</b><span>${item}</span></div>`).join('')}</div></div>`).join('')}</div></section>
    <section id="experience" class="section narrow">${heading('Experience', 'My professional journey')}<div class="timeline">${experience.map((item) => `<article class="timeline-card"><div class="timeline-marker"></div><div class="time-meta"><strong>${item.period}</strong><span>${item.location}</span></div><div class="timeline-body"><h3>${item.role}</h3><h4><img src="${item.logo || `https://www.google.com/s2/favicons?domain=${item.domain}&sz=64`}" alt="${item.company} logo"/>${item.company}</h4><ul>${item.bullets.map((bullet) => `<li>${bullet}</li>`).join('')}</ul>${tagList(item.tags)}</div></article>`).join('')}</div></section>
    <section id="highlights" class="section wide">${heading('Highlights', 'A few milestones beyond the day-to-day')}<div class="bento"><article class="bento-large"><span>400+</span><h3>DSA problems solved</h3><div class="coding-profiles"><a href="https://leetcode.com/u/dipesh99kumar/" target="_blank" rel="noreferrer"><img src="https://cdn.jsdelivr.net/npm/simple-icons@v15/icons/leetcode.svg" alt="LeetCode"/>LeetCode <b>↗</b></a><a href="https://www.geeksforgeeks.org/user/dipesh99kumar/" target="_blank" rel="noreferrer"><img src="https://cdn.jsdelivr.net/npm/simple-icons@v15/icons/geeksforgeeks.svg" alt="GeeksforGeeks"/>GeeksforGeeks <b>↗</b></a><a href="https://www.hackerrank.com/profile/dipesh99kumar" target="_blank" rel="noreferrer"><img src="https://cdn.jsdelivr.net/npm/simple-icons@v15/icons/hackerrank.svg" alt="HackerRank"/>HackerRank <b>↗</b></a></div></article><article><b>3+</b><h3>Years in AI engineering</h3><p>Building applied AI, RAG search, and agentic workflows.</p></article><article><b>6+</b><h3>Hackathons</h3><p>Participated in and earned multiple accolades.</p></article><article class="bento-wide"><span>Mentor. Build. Share.</span><p>Founded a student club to mentor juniors through technical sessions and knowledge-sharing initiatives.</p></article></div></section>
    <section id="certifications" class="section wide">${heading('Certifications', 'Credentials and learning milestones')}<div class="cert-grid">${certifications.map((cert) => `<article class="certificate"><div class="cert-preview"><img src="${cert.image}" alt="${cert.title} certificate" onerror="this.style.display='none'"/><div class="cert-placeholder"><span>Certificate</span><b>✦</b></div></div><div><p>${cert.issuer}</p><h3>${cert.title}</h3></div></article>`).join('')}</div></section>
    <section class="resume-cta section"><div><h2>Want to know more<i>?</i></h2><p>Download my resume for a detailed look at my experience, skills, and education.</p><a class="button primary" href="/dipesh_resume_1806.pdf" download>View Resume <b>↗</b></a></div></section>
    <section id="contact" class="section contact">${heading('Get in Touch', 'Have a project in mind or just want to say hello?')}<div class="contact-flow"><a href="mailto:${profile.email}" class="email-big">${profile.email} <b>↗</b></a><div class="contact-details"><span>⌖ ${profile.location}</span><span>◌ ${profile.phone}</span></div><div class="socials"><a href="${profile.github}" target="_blank" rel="noreferrer">GitHub</a><a href="${profile.linkedin}" target="_blank" rel="noreferrer">LinkedIn</a></div><a class="button primary" href="mailto:${profile.email}">Send me an email <b>↗</b></a></div></section>
  </main><footer><span>© 2026 ${profile.name}. All rights reserved.</span><div><a href="${profile.github}" target="_blank" rel="noreferrer">GitHub</a><a href="${profile.linkedin}" target="_blank" rel="noreferrer">LinkedIn</a></div></footer>`;

document.querySelector('.menu').addEventListener('click', () => document.querySelector('.nav-links').classList.toggle('open'));
const projectSection = document.querySelector('#projects');
projectSection.before(document.querySelector('#skills'), document.querySelector('#experience'));
const projectNav = document.querySelector('.nav-links a[href="#projects"]');
projectNav.before(document.querySelector('.nav-links a[href="#skills"]'), document.querySelector('.nav-links a[href="#experience"]'));
const navLinks = [...document.querySelectorAll('.nav-links a')];
navLinks.forEach((link) => link.addEventListener('click', () => document.querySelector('.nav-links').classList.remove('open')));
const observer = new IntersectionObserver((entries) => entries.forEach((entry) => { if (entry.isIntersecting) navLinks.forEach((link) => link.classList.toggle('active', link.hash === `#${entry.target.id}`)); }), { rootMargin: '-42% 0px -52% 0px' });
document.querySelectorAll('main section[id]').forEach((section) => observer.observe(section));
